name: Deploy to Azure

on:
  push:
    branches:
      - clean-branch
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for triggering the deployment'
        required: false
        default: 'Manual deployment'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rts-win-innovate'
        slot-name: 'dev'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
